---
- name: Installing apache
  hosts: all
  tasks:
    - name: Installing in appache server1
      yum:
        state: present
        name: httpd

    - name: Changing content in html file
      copy:
        content: "Content Editing using Ansible playbook"
        dest: /var/www/html/index.html

        # - name: Enabling the httpd
        # systemd:
        #enabled: yes
        #name: httpd

    - name: Collecting server public ipaddress
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
      register: myoutput

    - debug: msg="{{ myoutput }}"
    - set_fact: myvalue="{{ myoutput  }}"
